spring.datasource.url=jdbc:oracle:thin:@pokeshotsdle_high?TNS_ADMIN=/home/igor/oracle/wallet

spring.datasource.username=ADMIN
spring.datasource.password=Pokeshots01001001***

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ? FORÇAR USO DO JKS (resolve o erro SSO)
javax.net.ssl.trustStore=/home/igor/oracle/wallet/truststore.jks
javax.net.ssl.trustStorePassword=changeit

javax.net.ssl.keyStore=/home/igor/oracle/wallet/keystore.jks
javax.net.ssl.keyStorePassword=changeit

# ? MUITO IMPORTANTE
oracle.net.ssl_server_dn_match=true